inherit_from: .rubocop_todo.yml

Metrics/MethodLength:
  Max: 7
  Exclude:
    - 'bin/bundle'
    - 'db/migrate/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
